INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('1', 'Alli Donnett', 'Flight Attendant', '279');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('2', 'Frederick Wardrope', 'Flight Attendant', '334');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('3', 'Vicki Conkay', 'Cabin Crew', '292');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('4', 'Cris Whimpenny', 'Cabin Crew', '391');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('5', 'Duky Andrault', 'Cabin Services Supervisor', '106');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('6', 'Shela Urien', 'Captain', '342');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('7', 'Trey Bonelle', 'Medical Officer', '347');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('8', 'Whitby Dulanty', 'Junior Flight Attendant', '303');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('9', 'Paten McNeil', 'In-Flight Service Manager', '254');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('10', 'Evan Jolliss', 'Cabin Crew', '11');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('11', 'Giacomo Greenwell', 'Cabin Crew', '386');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('12', 'Stephanus Lesly', 'Flight Attendant', '33');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('13', 'Nicolette Strongitharm', 'In-Flight Service Manager', '198');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('14', 'Roxie Beszant', 'Cabin Crew', '83');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('15', 'Kenna Chander', 'Senior Flight Attendant', '403');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('16', 'Sandy Kacheller', 'Captain', '424');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('17', 'Elna Pidgeley', 'Flight Attendant', '261');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('18', 'Pedro Semarke', 'Flight Attendant', '123');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('19', 'Susanna Dive', 'Flight Attendant', '49');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('20', 'Saree Sterke', 'Cabin Crew', '320');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('21', 'Cammi Kinnach', 'Cabin Services Supervisor', '87');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('22', 'Ottilie Fildes', 'Captain', '407');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('23', 'Arnie Madelin', 'Cabin Crew', '195');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('24', 'Rory Shellcross', 'Cabin Crew', '487');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('25', 'Cyrillus Yaxley', 'Purser', '185');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('26', 'Elysee Sisland', 'Cabin Crew', '146');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('27', 'Samaria Huffa', 'Cabin Crew', '119');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('28', 'Zollie Heinrici', 'Cabin Services Director', '385');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('29', 'Kendal Derges', 'Junior Flight Attendant', '483');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('30', 'Oliy Jersh', 'Cabin Crew', '302');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('31', 'Katerine Pinsent', 'Senior Flight Attendant', '60');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('32', 'Karia Drover', 'Flight Attendant', '453');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('33', 'Tommie Giovannacc@i', 'Cabin Crew', '79');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('34', 'Florette Pullman', 'Flight Attendant', '154');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('35', 'Kora Kibbel', 'Senior Flight Attendant', '142');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('36', 'Edi Gilkison', 'Medical Officer', '98');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('37', 'Dew McCreary', 'Flight Attendant', '180');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('38', 'Lucas Mattioni', 'Cabin Crew', '80');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('39', 'Rakel Vasyukhnov', 'Second Officer', '272');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('40', 'Shelby Wisker', 'Cabin Crew', '78');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('41', 'Dov Ohrtmann', 'Flight Attendant', '226');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('42', 'Arabela Glasser', 'Cabin Crew', '79');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('43', 'Terencio Arsey', 'Flight Engineer', '146');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('44', 'Rab Colby', 'Cabin Crew', '38');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('45', 'Armando Hedderly', 'Safety Officer', '463');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('46', 'Zulema Garratty', 'Captain', '24');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('47', 'Pall Reveley', 'Cabin Crew', '466');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('48', 'Walt Wilkenson', 'Flight Attendant', '106');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('49', 'Ansell Dafforne', 'Cabin Services Supervisor', '227');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('50', 'Carley Clail', 'Cabin Crew', '487');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('51', 'Romy Juschke', 'Flight Attendant', '193');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('52', 'Moss McNickle', 'Flight Attendant', '65');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('53', 'Cleveland Blaxter', 'Cabin Crew', '140');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('54', 'Martina Bellenie', 'Cabin Services Supervisor', '386');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('55', 'Sella Wilmott', 'Junior Flight Attendant', '236');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('56', 'Eulalie Coneybeare', 'Cabin Crew', '183');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('57', 'Freddie Gloucester', 'First Officer', '154');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('58', 'Adriano Graddell', 'Flight Attendant', '10');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('59', 'Dell McGurn', 'In-Flight Service Manager', '328');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('60', 'Rosanne Bourton', 'Cabin Crew', '85');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('61', 'Suzi Dominichelli', 'Flight Attendant', '385');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('62', 'Lela Lombard', 'Junior Flight Attendant', '450');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('63', 'Lottie Coatman', 'Cabin Crew', '85');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('64', 'Millisent Barbrick', 'Flight Attendant', '312');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('65', 'Sergent Ganderton', 'Junior Flight Attendant', '51');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('66', 'Briney Harron', 'Second Officer', '405');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('67', 'Gregoire Howman', 'Safety Officer', '387');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('68', 'Ilsa Hudless', 'Cabin Crew', '83');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('69', 'Tarra OScanlan', 'In-Flight Service Manager', '397');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('70', 'Vite Wasiela', 'Cabin Crew', '254');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('71', 'Loutitia Dummer', 'Second Officer', '268');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('72', 'Gerhardt Manilow', 'Cabin Crew', '442');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('73', 'Di McElroy', 'Flight Attendant', '9');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('74', 'Marwin Freeland', 'Second Officer', '211');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('75', 'Julianne MacAnellye', 'Captain', '274');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('76', 'Laura Marler', 'Flight Attendant', '299');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('77', 'Daloris Gonzalez', 'In-Flight Service Manager', '395');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('78', 'Clara Maier', 'Purser', '470');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('79', 'Catlee Delleschi', 'Cabin Crew', '366');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('80', 'Lori Shovlin', 'Flight Attendant', '380');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('81', 'Sosanna Sarver', 'Cabin Crew', '106');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('82', 'Alonso Fussie', 'Flight Attendant', '285');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('83', 'Lawton Whittier', 'Cabin Crew', '152');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('84', 'Marysa Siret', 'Cabin Crew', '407');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('85', 'Mead Romans', 'Cabin Services Director', '452');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('86', 'Lark MacGow', 'Junior Flight Attendant', '252');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('87', 'Pip McQuie', 'Safety Officer', '178');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('88', 'Selig Wragge', 'Cabin Crew', '239');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('89', 'Jerrome Wildman', 'Cabin Services Supervisor', '284');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('90', 'Carmelita Listone', 'Senior Flight Attendant', '33');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('91', 'Jesus Skipsey', 'Cabin Crew', '417');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('92', 'Anders Brooksby', 'Cabin Crew', '470');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('93', 'Darcee Jizhaki', 'Flight Attendant', '333');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('94', 'Delmore Brauns', 'Cabin Crew', '175');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('95', 'Guthry Marshland', 'Flight Attendant', '151');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('96', 'Sharlene Oglesbee', 'Junior Flight Attendant', '274');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('97', 'Teddi Eeles', 'Cabin Crew', '157');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('98', 'Casey De Ferraris', 'Cabin Crew', '259');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('99', 'Vally Maureen', 'Flight Attendant', '488');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('100', 'Noam McTrusty', 'First Officer', '411');
