INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('101', 'Sander Wallicker', 'Cabin Crew', '1033');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('102', 'Sari Lillo', 'Cabin Crew', '1181');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('103', 'Lin Gabb', 'In-Flight Service Manager', '1224');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('104', 'Debbi Delicate', 'Purser', '1461');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('105', 'Brietta Braban', 'Junior Flight Attendant', '1079');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('106', 'Elenore Jess', 'Flight Attendant', '1118');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('107', 'Lambert Manicomb', 'In-Flight Service Manager', '1172');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('108', 'Marco Harner', 'Cabin Crew', '1159');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('109', 'Rosetta Hylton', 'Flight Attendant', '1481');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('110', 'Liesa Falcus', 'Cabin Crew', '1125');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('111', 'Johnathan Desport', 'Junior Flight Attendant', '1009');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('112', 'Flossie Whyteman', 'Senior Flight Attendant', '1489');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('113', 'Thorndike Vivers', 'Cabin Crew', '1038');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('114', 'Weston Billsberry', 'Cabin Crew', '1002');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('115', 'Denni deKnevet', 'Junior Flight Attendant', '1254');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('116', 'Skipp Brouard', 'Cabin Crew', '1086');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('117', 'Johnnie Smitton', 'First Officer', '1118');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('118', 'Grantham Farnin', 'Cabin Services Supervisor', '1397');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('119', 'Tuck Bugs', 'Second Officer', '1451');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('120', 'Odille Krause', 'Cabin Crew', '1185');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('121', 'Dixie Quarrington', 'Cabin Services Supervisor', '1458');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('122', 'Doretta MacKerley', 'Cabin Crew', '1496');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('123', 'Derk Sellack', 'Cabin Services Supervisor', '1406');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('124', 'Marnie Rowson', 'Flight Attendant', '1363');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('125', 'Dione Hurtado', 'Flight Attendant', '1247');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('126', 'Loise Nelsen', 'Cabin Crew', '1197');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('127', 'Stanleigh Pickerin', 'Medical Officer', '1473');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('128', 'Arlina Cresser', 'In-Flight Service Manager', '1134');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('129', 'Keeley Jefford', 'Flight Attendant', '1227');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('130', 'Suzi MacMurray', 'Flight Attendant', '1346');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('131', 'Alica Allwood', 'Cabin Crew', '1170');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('132', 'Hersh Tregust', 'Cabin Crew', '1347');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('133', 'Blondelle Pinch', 'Flight Attendant', '1170');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('134', 'Herold Furniss', 'Lead Flight Attendant', '1419');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('135', 'Brenden Millichip', 'Senior Flight Attendant', '1384');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('136', 'Marchelle Purselow', 'Flight Attendant', '1026');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('137', 'Tomi Holdin', 'Safety Officer', '1154');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('138', 'Morgen Bromhead', 'Flight Attendant', '1413');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('139', 'Julianne Livermore', 'Junior Flight Attendant', '1183');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('140', 'Elijah Medler', 'Flight Attendant', '1373');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('141', 'Zeb Dalliston', 'Flight Attendant', '1359');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('142', 'Blondie Amorine', 'Captain', '1185');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('143', 'Georas Brymham', 'Cabin Crew', '1170');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('144', 'Twila Gaspero', 'Flight Attendant', '1249');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('145', 'Jenda Gopsall', 'Purser', '1153');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('146', 'Cyril Dalli', 'Cabin Crew', '1007');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('147', 'Vivienne Piercy', 'Cabin Crew', '1178');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('148', 'Tisha Gerlack', 'Flight Attendant', '1029');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('149', 'Jeanie Norcross', 'Cabin Crew', '1332');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('150', 'Wiatt Milne', 'Cabin Crew', '1401');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('151', 'Lebbie Berrane', 'Safety Officer', '1180');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('152', 'Caye Mowles', 'Flight Attendant', '1384');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('153', 'Rufus Honig', 'Cabin Crew', '1282');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('154', 'Spenser Ephson', 'Junior Flight Attendant', '1074');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('155', 'Orella Varran', 'Senior Flight Attendant', '1389');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('156', 'Christos Simonassi', 'Cabin Crew', '1290');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('157', 'Elvera Froment', 'Junior Flight Attendant', '1463');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('158', 'Abelard Danihelka', 'Cabin Crew', '1192');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('159', 'Chelsae Coughan', 'Cabin Crew', '1246');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('160', 'Minor Redfearn', 'Lead Flight Attendant', '1001');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('161', 'Winn Denton', 'Junior Flight Attendant', '1208');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('162', 'Neda Nail', 'Cabin Crew', '1448');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('163', 'Reinald Reddel', 'Cabin Crew', '1246');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('164', 'Biddy Carnihan', 'Flight Attendant', '1132');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('165', 'Gaylor Chidzoy', 'Cabin Crew', '1095');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('166', 'Mose Baptist', 'Cabin Crew', '1159');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('167', 'Curtice McCallum', 'Medical Officer', '1105');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('168', 'Sybila Bunkle', 'In-Flight Service Manager', '1470');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('169', 'Jordan Faucherand', 'Lead Flight Attendant', '1059');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('170', 'Sissie Dast', 'Cabin Crew', '1142');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('171', 'Charmain Risson', 'Second Officer', '1352');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('172', 'Richard Hemerijk', 'First Officer', '1385');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('173', 'Ninnette Rymill', 'Cabin Crew', '1116');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('174', 'Renaud De la Eglise', 'Junior Flight Attendant', '1084');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('175', 'Elberta Porcher', 'Lead Flight Attendant', '1205');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('176', 'Kamilah Finby', 'Cabin Crew', '1362');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('177', 'Flem Dwire', 'Cabin Crew', '1341');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('178', 'Brigitta Guidini', 'Cabin Services Supervisor', '1033');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('179', 'Anselm OTeague', 'Cabin Crew', '1374');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('180', 'Annabal Burrett', 'First Officer', '1303');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('181', 'Jeni Haberjam', 'Cabin Crew', '1499');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('182', 'Sarene Carolan', 'Cabin Crew', '1313');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('183', 'Blake Dowears', 'Captain', '1309');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('184', 'Manda Taillard', 'In-Flight Service Manager', '1287');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('185', 'Gail Aldwich', 'Cabin Crew', '1323');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('186', 'Vin Dohr', 'Flight Engineer', '1452');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('187', 'Jonah Yablsley', 'Cabin Services Supervisor', '1293');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('188', 'Jimmie Cuppitt', 'Cabin Crew', '1018');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('189', 'Drusy Schruurs', 'Cabin Crew', '1390');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('190', 'Bibby Craze', 'Cabin Crew', '1326');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('191', 'Mal Bartrop', 'Flight Attendant', '1228');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('192', 'Garreth Segges', 'First Officer', '1489');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('193', 'Tammy Buttery', 'Captain', '1350');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('194', 'Denyse Schops', 'Lead Flight Attendant', '1008');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('195', 'Jamima Mathwen', 'Cabin Crew', '1362');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('196', 'Lynett Rudkin', 'Second Officer', '1487');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('197', 'Haroun Nutten', 'Cabin Crew', '1001');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('198', 'Anne-marie Edmundson', 'Cabin Crew', '1469');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('199', 'Tommie Syms', 'Cabin Crew', '1336');
INSERT INTO CrewMembers(CREW_ID, CREW_NAME, CREW_ROLE, FLIGHT_ID) VALUES ('200', 'Anderson Killich', 'Senior Flight Attendant', '1353');
commit;