insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (1, '''Pilatus PC-12''', 422);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (2, '''Airbus A340''', 291);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (3, '''Embraer E175''', 357);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (4, '''Airbus A340''', 269);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (5, '''Airbus A350''', 266);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (6, '''McDonnell Douglas MD-11''', 220);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (7, '''Cessna 172''', 373);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (8, '''Airbus A320''', 313);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (9, '''McDonnell Douglas DC-10''', 438);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (10, '''Pilatus PC-12''', 264);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (11, '''Gulfstream G650''', 345);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (12, '''McDonnell Douglas MD-11''', 341);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (13, '''Airbus A330''', 368);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (14, '''Dassault Falcon 2000''', 320);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (15, '''Tupolev Tu-204''', 293);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (16, '''Embraer E190''', 361);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (17, '''McDonnell Douglas MD-11''', 415);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (18, '''Bombardier CRJ900''', 234);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (19, '''Pilatus PC-24''', 383);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (20, '''Embraer E175''', 371);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (21, '''Boeing 787 Dreamliner''', 444);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (22, '''Airbus A220''', 221);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (23, '''Airbus A330''', 274);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (24, '''McDonnell Douglas MD-11''', 206);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (25, '''Embraer E175''', 314);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (26, '''Pilatus PC-24''', 226);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (27, '''Boeing 767''', 202);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (28, '''Antonov An-158''', 356);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (29, '''Embraer E195''', 261);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (30, '''Boeing 720''', 341);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (31, '''Lockheed L-1011''', 203);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (32, '''Airbus A320''', 369);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (33, '''Comac C919''', 234);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (34, '''Beechcraft King Air 250''', 372);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (35, '''Boeing 777''', 315);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (36, '''Pilatus PC-24''', 230);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (37, '''Gulfstream G650''', 407);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (38, '''Boeing 720''', 286);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (39, '''Boeing 720''', 357);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (40, '''Cessna 182''', 370);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (41, '''Beechcraft King Air 350''', 285);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (42, '''Bombardier CRJ700''', 303);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (43, '''Boeing 720''', 244);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (44, '''Comac C919''', 350);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (45, '''Pilatus PC-12''', 364);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (46, '''Airbus A340''', 421);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (47, '''Tupolev Tu-204''', 362);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (48, '''Gulfstream G550''', 424);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (49, '''Embraer E190''', 396);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (50, '''Embraer E175''', 292);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (51, '''Lockheed L-1011''', 254);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (52, '''Pilatus PC-12''', 257);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (53, '''Ilyushin Il-96''', 207);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (54, '''Embraer E195''', 346);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (55, '''Dassault Falcon 2000''', 336);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (56, '''Bombardier CRJ700''', 404);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (57, '''Boeing 737''', 213);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (58, '''Sukhoi Superjet 100''', 348);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (59, '''Boeing 787 Dreamliner''', 290);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (60, '''Dassault Falcon 7X''', 354);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (61, '''Boeing 767''', 328);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (62, '''Airbus A340''', 339);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (63, '''Comac C919''', 278);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (64, '''Bombardier Q400''', 347);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (65, '''McDonnell Douglas DC-10''', 330);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (66, '''Beechcraft King Air 250''', 325);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (67, '''Boeing 767''', 308);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (68, '''Sukhoi Superjet 100''', 375);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (69, '''Beechcraft King Air 350''', 267);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (70, '''Embraer E190''', 205);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (71, '''Boeing 727''', 401);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (72, '''Antonov An-158''', 234);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (73, '''Airbus A340''', 408);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (74, '''Bombardier CS300''', 431);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (75, '''Comac C919''', 448);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (76, '''Gulfstream G550''', 383);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (77, '''Boeing 720''', 302);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (78, '''Pilatus PC-12''', 309);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (79, '''Airbus A321''', 370);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (80, '''Bombardier CRJ900''', 368);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (81, '''Pilatus PC-12''', 226);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (82, '''Bombardier CRJ700''', 367);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (83, '''Sukhoi Superjet 100''', 367);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (84, '''Beechcraft King Air 350''', 384);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (85, '''Cessna Citation X''', 283);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (86, '''Gulfstream G650''', 413);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (87, '''Tupolev Tu-204''', 405);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (88, '''Boeing 720''', 254);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (89, '''Airbus A330''', 431);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (90, '''Boeing 737''', 272);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (91, '''Dassault Falcon 7X''', 313);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (92, '''Gulfstream G650''', 388);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (93, '''Pilatus PC-12''', 277);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (94, '''Boeing 757''', 285);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (95, '''Pilatus PC-12''', 419);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (96, '''Cessna 182''', 268);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (97, '''Airbus A380''', 419);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (98, '''Boeing 747''', 308);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (99, '''Boeing 720''', 274);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (100, '''Gulfstream G550''', 391);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (101, '''Tupolev Tu-204''', 247);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (102, '''Boeing 727''', 302);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (103, '''Ilyushin Il-96''', 231);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (104, '''Bombardier Q400''', 269);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (105, '''Airbus A340''', 395);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (106, '''Airbus A321''', 311);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (107, '''Airbus A350''', 258);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (108, '''Embraer E195''', 448);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (109, '''Sukhoi Superjet 100''', 324);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (110, '''Airbus A380''', 279);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (111, '''Tupolev Tu-214''', 342);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (112, '''Airbus A320''', 320);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (113, '''Cessna 172''', 210);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (114, '''Dassault Falcon 2000''', 386);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (115, '''Airbus A320''', 293);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (116, '''Mitsubishi Regional Jet''', 369);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (117, '''Boeing 727''', 441);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (118, '''Dassault Falcon 7X''', 408);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (119, '''Bombardier CS100''', 382);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (120, '''Boeing 717''', 415);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (121, '''McDonnell Douglas DC-10''', 402);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (122, '''Bombardier CS100''', 250);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (123, '''Cessna Citation X''', 233);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (124, '''Pilatus PC-12''', 394);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (125, '''Ilyushin Il-96''', 317);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (126, '''Lockheed L-1011''', 429);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (127, '''Gulfstream G550''', 371);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (128, '''Cessna Citation X''', 347);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (129, '''Embraer E190''', 295);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (130, '''Airbus A350''', 383);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (131, '''Airbus A330''', 391);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (132, '''Gulfstream G550''', 248);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (133, '''Embraer E195''', 343);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (134, '''Embraer E190''', 248);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (135, '''Bombardier CS300''', 204);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (136, '''Pilatus PC-24''', 223);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (137, '''Airbus A310''', 422);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (138, '''Comac C919''', 263);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (139, '''Dassault Falcon 2000''', 430);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (140, '''McDonnell Douglas MD-11''', 438);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (141, '''Cessna 182''', 415);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (142, '''Airbus A321''', 208);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (143, '''Bombardier Q400''', 425);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (144, '''Antonov An-148''', 326);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (145, '''Airbus A220''', 223);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (146, '''Pilatus PC-24''', 242);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (147, '''Cessna Citation X''', 287);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (148, '''Sukhoi Superjet 100''', 280);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (149, '''Boeing 777''', 268);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (150, '''Bombardier CS100''', 366);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (151, '''Lockheed L-1011''', 249);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (152, '''Boeing 767''', 390);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (153, '''Dassault Falcon 7X''', 406);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (154, '''Boeing 787 Dreamliner''', 259);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (155, '''McDonnell Douglas MD-11''', 238);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (156, '''Airbus A320''', 391);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (157, '''Cessna 172''', 317);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (158, '''Airbus A340''', 311);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (159, '''Airbus A330''', 374);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (160, '''McDonnell Douglas MD-11''', 431);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (161, '''Embraer E195''', 302);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (162, '''Boeing 747''', 241);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (163, '''Antonov An-158''', 424);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (164, '''Embraer E190''', 441);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (165, '''Airbus A220''', 205);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (166, '''Antonov An-158''', 243);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (167, '''Bombardier CRJ200''', 246);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (168, '''Antonov An-158''', 333);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (169, '''Bombardier Q400''', 327);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (170, '''Cessna 172''', 441);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (171, '''Bombardier CS100''', 363);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (172, '''Airbus A321''', 227);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (173, '''Bombardier CRJ900''', 449);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (174, '''Boeing 727''', 320);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (175, '''Beechcraft King Air 250''', 300);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (176, '''Pilatus PC-12''', 299);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (177, '''Boeing 727''', 205);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (178, '''McDonnell Douglas DC-10''', 219);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (179, '''Boeing 757''', 294);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (180, '''Airbus A330''', 289);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (181, '''Airbus A380''', 412);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (182, '''Gulfstream G550''', 321);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (183, '''Airbus A320''', 375);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (184, '''Boeing 777''', 277);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (185, '''Embraer E175''', 426);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (186, '''Bombardier CS300''', 372);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (187, '''Airbus A321''', 316);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (188, '''Airbus A340''', 301);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (189, '''Airbus A310''', 325);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (190, '''Boeing 787 Dreamliner''', 228);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (191, '''Gulfstream G550''', 359);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (192, '''Dassault Falcon 2000''', 293);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (193, '''Airbus A321''', 420);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (194, '''Bombardier CRJ700''', 446);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (195, '''Boeing 757''', 341);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (196, '''Dassault Falcon 2000''', 399);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (197, '''Embraer E190''', 249);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (198, '''Pilatus PC-12''', 232);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (199, '''Bombardier CS300''', 342);
insert into Aircraft (AIRCRAFT_ID, AIRCRAFT_TYPE, CAPACITY) values (200, '''Airbus A350''', 367);
