insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (1, '''JetSky Airlines''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (2, '''AeroLink''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (3, '''SkyHigh Airways''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (4, '''StarFlyer''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (5, '''AirWave''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (6, '''FlyAway''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (7, '''SkyConnect''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (8, '''EagleAir''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (9, '''CloudNine Airlines''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (10, '''BlueSky Aviation''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (11, '''Sunrise Airways''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (12, '''Nimbus Airlines''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (13, '''VistaJet''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (14, '''GlobalWings''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (15, '''Harmony Air''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (16, '''AirHorizon''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (17, '''SwiftAir''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (18, '''VistaFly''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (19, '''Summit Airlines''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (20, '''AirQuest''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (21, '''Pioneer Air''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (22, '''Alpha Airlines''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (23, '''JourneyJet''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (24, '''Infinity Air''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (25, '''AirVenture''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (26, '''SkyQuest''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (27, '''PrimeAir''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (28, '''Galactic Airways''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (29, '''SkyVoyage''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (30, '''Nova Airlines''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (31, '''Explorer Air''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (32, '''Majestic Airlines''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (33, '''ApexAir''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (34, '''SkyGuard''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (35, '''Wingspan Airways''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (36, '''Skyline Air''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (37, '''Frontier Wings''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (38, '''Ascend Air''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (39, '''SkyBound''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (40, '''Eclipse Airways''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (41, '''SkyBridge''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (42, '''Radiant Air''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (43, '''OmniAir''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (44, '''Celestial Airlines''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (45, '''Zenith Air''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (46, '''AirVoyager''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (47, '''SkyGlide''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (48, '''Pinnacle Airlines''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (49, '''Altitude Air''');
insert into Airlines (AIRLINE_ID, AIRLINE_NAME) values (50, '''Voyager Airways''');
