insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (1, 'KAM', 'Ibabang Tayuman');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (2, 'YNG', 'Gorzyce');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (3, 'LZC', 'Jiaoxie');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (4, 'SDS', 'Villach');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (5, 'PRP', 'Alfonso');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (6, 'QEF', 'Shijiao');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (7, 'VQQ', 'Capela');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (8, 'YDC', 'Mgandu');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (9, 'IHN', 'Marne-la-Vallée');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (10, 'PZE', 'Baih');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (11, 'PLR', 'Inta');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (12, 'GUD', 'Madīnat Ḩamad');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (13, 'MZD', 'Beijie');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (14, 'NLC', 'Krasnyy Oktyabr’');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (15, 'PVA', 'Senggreng');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (16, 'ARW', 'Betong');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (17, 'BWG', 'Skaudvilė');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (18, 'TOU', 'Haliut');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (19, 'AAA', 'Ishqoshim');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (20, 'LYG', 'Bangelan');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (21, 'BYW', 'Tayang');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (22, 'BHD', 'Stettler');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (23, 'MBZ', 'Tsimkavichy');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (24, 'RNS', 'Sokal’');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (25, 'WBC', 'Jāmpur');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (26, 'LCJ', 'Toulouse');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (27, 'PDO', 'Changchi');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (28, 'INO', 'Kurayoshi');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (29, 'DDM', 'Brochów');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (30, 'LOD', 'Bhunya');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (31, 'LKG', 'Yanggu');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (32, 'MQZ', 'Estelí');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (33, 'ANQ', 'Liuji');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (34, 'DUA', 'Stockholm');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (35, 'WKI', 'Lyeskawka');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (36, 'TPG', 'Pires do Rio');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (37, 'OCN', 'Baiyun');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (38, 'YOG', 'Álimos');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (39, 'TET', 'Ngurore');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (40, 'LYH', 'Évreux');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (41, 'VPN', 'Puerres');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (42, 'UTU', 'Namyangju');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (43, 'SDT', 'Moncada');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (44, 'YPM', 'Las Parejas');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (45, 'APK', 'Atap');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (46, 'IIA', 'Aix-en-Provence');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (47, 'FUL', 'Sumberjeruk');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (48, 'LIG', 'Lodoyo');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (49, 'LAQ', 'Khyzy');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (50, 'VYI', 'Trelew');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (51, 'MGF', 'Lishu');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (52, 'HOG', 'Haodian');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (53, 'TNZ', 'Ūdalah');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (54, 'YCK', 'Zhelin');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (55, 'ENY', 'Loivos');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (56, 'PBC', 'Shuanghekou');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (57, 'ETH', 'Douane');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (58, 'KLG', 'Khabarovsk');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (59, 'XCL', 'Thị Trấn Phù Yên');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (60, 'TEV', 'Baziqiao');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (61, 'WUM', 'Thị Trấn Phú Mỹ');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (62, 'STK', 'Emmaboda');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (63, 'YHD', 'Qinjia');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (64, 'GNA', 'Göteborg');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (65, 'CMX', 'Hekou');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (66, 'HOU', 'Ḩakamā');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (67, '0', 'Czchów');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (68, 'CSR', 'Carenang Lor');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (69, 'DGW', 'Dublin');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (70, 'SMO', 'Oslo');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (71, 'BLX', 'San Jacinto');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (72, 'HMJ', 'Tervel');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (73, 'GWW', 'Gamleby');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (74, 'NML', 'Khadan Khāk');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (75, 'OBO', 'Dahe');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (76, 'XMI', 'El Fureidīs');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (77, 'NBS', 'Qionghai');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (78, 'PYJ', 'Panao');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (79, 'DPE', 'Al Karāmah');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (80, 'ACX', 'Quva');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (81, 'OPU', 'Jeong');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (82, 'KNF', 'Taling Chan');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (83, 'UCE', 'Kameyama');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (84, 'CLE', 'Verkhniy Landekh');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (85, 'CHL', 'Besançon');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (86, 'YAU', 'Pushkino');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (87, 'INT', 'Zhangjiagang');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (88, 'OKI', 'Zengjia');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (89, 'LGP', 'Bulan');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (90, 'NKN', 'Ambam');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (91, 'PNQ', 'Pinheiros');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (92, 'OPS', 'Hulan');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (93, 'BDM', 'Dali');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (94, 'KHY', 'Yambrasbamba');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (95, 'SBB', 'Siao');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (96, 'GCI', 'Jianxin');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (97, 'HKS', 'Hualgayoc');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (98, 'ILY', 'Digkilaan');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (99, 'ZNC', 'Yushugou');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (100, 'IRU', 'Candelaria');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (101, 'CBM', 'Bunisari');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (102, 'AYS', 'Banovo Polje');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (103, 'IWJ', 'Barrosa');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (104, 'ARF', 'Lukulu');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (105, 'AKJ', 'Konstantinovsk');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (106, 'ITH', 'Aţ Ţawāḩīn');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (107, 'SAL', 'Shanghu');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (108, 'GLK', 'Manolo Fortich');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (109, 'LYA', 'Pendawanbaru');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (110, 'SSB', 'Huangjin');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (111, 'LFM', 'Sobang');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (112, 'WOL', 'Saynshand');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (113, 'UVA', 'Brandsen');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (114, 'ARK', 'Fada N''gourma');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (115, 'SFH', 'Guacarí');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (116, 'CHK', 'Olszanica');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (117, 'BCM', 'Zhangzhu');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (118, 'CFM', 'Taiba');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (119, 'YCM', 'Fuzhiping');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (120, 'YQL', 'Santa Cruz Muluá');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (121, 'NPE', 'Ciechanowiec');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (122, 'BLL', 'Lunsar');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (123, 'LBI', 'Mander');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (124, 'LSC', 'Qincheng');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (125, 'MMT', 'Fusheng');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (126, 'JVA', 'Buenlag');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (127, 'CDG', 'Nagorsk');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (128, 'MCD', 'Aqaba');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (129, 'BDH', 'Qingkenpao');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (130, 'BLQ', 'Angers');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (131, 'LWH', 'El Carmen');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (132, 'LCL', 'Paranapanema');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (133, 'TLN', 'Wangcun');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (134, 'AYS', 'Kybartai');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (135, 'LCG', 'Majdal Banī Fāḑil');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (136, 'XOG', 'Savigny-le-Temple');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (137, 'KNS', 'Yixi');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (138, 'BHC', 'Camajuaní');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (139, 'LUZ', 'Krasnyy Oktyabr’');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (140, 'CLG', 'Mporokoso');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (141, 'KSV', 'Boussé');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (142, 'IHR', 'Bogorejo');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (143, 'MTJ', 'Daga');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (144, 'BJG', 'Cawayan');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (145, 'MGU', 'Shabo');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (146, 'YTR', 'Tokuyama');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (147, 'MOC', 'Jinnan');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (148, 'DNK', 'Bagarmossen');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (149, 'OYO', 'Maicao');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (150, 'OAR', 'Baoshan');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (151, 'NDF', 'Gampaha');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (152, 'ASU', 'Nentón');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (153, 'KHE', 'Västervik');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (154, 'ZHM', 'Neuilly-sur-Seine');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (155, 'TUP', 'Itaguaçu');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (156, 'GRO', 'Ad Dīs ash Sharqīyah');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (157, 'VLV', 'Longmiao');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (158, 'COA', 'Xuhang');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (159, 'GKD', 'Zblewo');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (160, 'HYL', 'Zabaykal’sk');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (161, 'ZFN', 'Boca de Parita');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (162, 'RKU', 'Dukuhsawah');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (163, 'BUY', 'Chyšky');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (164, 'LBF', 'Beaumont');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (165, 'ISQ', 'Lijia');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (166, 'QNC', 'Qiankou');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (167, 'PUZ', 'Shenji');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (168, 'CII', 'Xuefu');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (169, 'MON', 'Farīdpur');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (170, 'KIE', 'Jati');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (171, 'MBZ', 'Pailiao');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (172, 'KLE', 'Kokkónion');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (173, 'FLM', 'Haapajärvi');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (174, 'URI', 'Monte da Pedra');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (175, 'UAL', 'Chambishi');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (176, 'MSE', 'Brańsk');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (177, 'YSV', 'Santa Bernardina');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (178, 'UUS', 'Terara');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (179, 'ARL', 'Česká Skalice');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (180, 'KII', 'Conchamarca');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (181, 'APU', 'Pagedangan');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (182, 'SNJ', 'Jincheng');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (183, 'IGG', 'Trelleborg');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (184, 'TFY', 'Acacías');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (185, 'JUI', 'Londrina');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (186, 'YAU', 'Bestala');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (187, 'KON', 'Gorna Oryakhovitsa');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (188, 'HLD', 'Carpiquet');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (189, 'AQS', 'Loureiro');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (190, 'KWZ', 'Barţa‘ah ash Sharqīyah');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (191, 'SSG', 'Calanogas');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (192, 'QKX', 'Yanqi');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (193, 'SYP', 'Tongyang');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (194, 'PUB', 'Melaka');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (195, '0', 'Karibib');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (196, 'GIS', 'Kralice na Hané');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (197, 'KGU', 'Ash Shawātī');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (198, 'SBT', 'Richmond');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (199, 'JOT', 'Alpiarça');
insert into Airports (AIRPORT_ID, AIRPORT_NAME, LOCATION) values (200, 'TIW', 'Winston Salem');
