ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
SELECT p.PASSENGER_NAME, f.FLIGHT_NUMBER, f.DEPARTURE_TIME, f.ARRIVAL_TIME
FROM Passengers p
JOIN Bookings b ON p.PASSENGER_ID = b.PASSENGER_ID
JOIN Flights f ON b.FLIGHT_ID = f.FLIGHT_ID
WHERE f.DEPARTURE_AIRPORT = (SELECT AIRPORT_ID FROM Airports WHERE LOCATION = 'JFK')
AND f.DEPARTURE_TIME >= TO_DATE('2024-05-15') AND f.DEPARTURE_TIME < TO_DATE('2024-05-16');