SELECT f.FLIGHT_NUMBER, dep.AIRPORT_NAME AS DEPARTURE_AIRPORT, arr.AIRPORT_NAME AS ARRIVAL_AIRPORT, a.AIRCRAFT_TYPE, al.AIRLINE_NAME
FROM Flights f
JOIN Airports dep ON f.DEPARTURE_AIRPORT = dep.AIRPORT_ID
JOIN Airports arr ON f.ARRIVAL_AIRPORT = arr.AIRPORT_ID
JOIN Aircraft a ON f.AIRCRAFT_ID = a.AIRCRAFT_ID
JOIN Airlines al ON f.AIRLINE_ID = al.AIRLINE_ID
WHERE a.AIRCRAFT_TYPE = 'Boeing 737';