SELECT f.FLIGHT_NUMBER, COUNT(b.BOOKING_ID) AS TOTAL_BOOKINGS, AVG(p.PASSENGER_AGE) AS AVG_PASSENGER_AGE
FROM Flights f
LEFT JOIN Bookings b ON f.FLIGHT_ID = b.FLIGHT_ID
LEFT JOIN Passengers p ON b.PASSENGER_ID = p.PASSENGER_ID
GROUP BY f.FLIGHT_NUMBER
ORDER BY f.FLIGHT_NUMBER;