SELECT cm.CREW_NAME, cm.CREW_ROLE
FROM CrewMembers cm
JOIN Flights f ON cm.FLIGHT_ID = f.FLIGHT_ID
WHERE f.DEPARTURE_AIRPORT = (SELECT AIRPORT_ID FROM Airports WHERE AIRPORT_NAME = 'JFK Airport New York')
 AND f.ARRIVAL_AIRPORT = (SELECT AIRPORT_ID FROM Airports WHERE AIRPORT_NAME = 'LAX Airport Los Angeles')
 AND f.DEPARTURE_TIME >= '2024-05-15' AND f.DEPARTURE_TIME < '2024-05-15';