insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (1, 'Boeing 737', 456);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (2, 'Bombardier CS300', 518);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (3, 'Comac C919', 610);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (4, 'Airbus A220', 479);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (5, 'ATR 72', 627);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (6, 'Comac C919', 479);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (7, 'ATR 72', 581);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (8, 'ATR 72', 612);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (9, 'Dornier Do 328', 466);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (10, 'Boeing 737', 579);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (11, 'Embraer 190', 495);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (12, 'ATR 72', 623);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (13, 'Bombardier CRJ700', 556);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (14, 'Airbus A330', 448);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (15, 'De Havilland Canada DHC-8-400', 460);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (16, 'Antonov An-148', 657);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (17, 'Airbus A350', 678);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (18, 'ATR 72', 511);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (19, 'Comac C919', 494);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (20, 'Airbus A350', 522);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (21, 'Airbus A220', 595);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (22, 'Airbus A320', 659);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (23, 'Mitsubishi MRJ90', 676);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (24, 'Xian MA60', 471);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (25, 'ATR 72', 653);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (26, 'Boeing 747', 683);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (27, 'Airbus A320', 618);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (28, 'Airbus A380', 503);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (29, 'Xian MA60', 648);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (30, 'Boeing 787 Dreamliner', 679);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (31, 'Sukhoi Superjet 100', 427);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (32, 'Xian MA60', 640);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (33, 'Airbus A380', 517);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (34, 'Airbus A320', 444);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (35, 'Dornier Do 328', 659);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (36, 'Airbus A220', 518);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (37, 'Dornier Do 328', 529);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (38, 'Airbus A380', 487);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (39, 'ATR 72', 575);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (40, 'Boeing 787 Dreamliner', 531);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (41, 'Airbus A220', 548);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (42, 'Airbus A320', 460);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (43, 'Xian MA60', 594);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (44, 'Dornier Do 328', 529);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (45, 'Bombardier CRJ700', 584);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (46, 'Boeing 787 Dreamliner', 634);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (47, 'Airbus A320', 550);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (48, 'Boeing 747', 548);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (49, 'Boeing 747', 482);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (50, 'Comac C919', 514);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (51, 'Airbus A380', 559);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (52, 'Dornier Do 328', 422);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (53, 'Comac C919', 490);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (54, 'Boeing 777', 496);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (55, 'Embraer 190', 610);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (56, 'Comac C919', 437);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (57, 'Boeing 747', 496);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (58, 'ATR 72', 540);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (59, 'Airbus A220', 572);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (60, 'Airbus A320', 636);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (61, 'Boeing 737', 644);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (62, 'Airbus A350', 596);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (63, 'ATR 72', 601);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (64, 'Airbus A330', 554);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (65, 'Bombardier CS300', 403);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (66, 'Boeing 787 Dreamliner', 573);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (67, 'Boeing 777', 552);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (68, 'Boeing 777', 465);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (69, 'Airbus A220', 678);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (70, 'Boeing 747', 562);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (71, 'Mitsubishi MRJ90', 484);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (72, 'De Havilland Canada DHC-8-400', 422);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (73, 'Airbus A220', 634);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (74, 'Antonov An-148', 692);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (75, 'Bombardier CRJ700', 569);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (76, 'Xian MA60', 688);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (77, 'Boeing 787 Dreamliner', 617);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (78, 'Boeing 777', 404);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (79, 'Airbus A220', 477);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (80, 'Airbus A220', 460);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (81, 'Airbus A220', 587);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (82, 'Boeing 747', 580);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (83, 'Antonov An-148', 493);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (84, 'Airbus A380', 516);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (85, 'Antonov An-148', 602);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (86, 'Comac C919', 615);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (87, 'Sukhoi Superjet 100', 640);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (88, 'De Havilland Canada DHC-8-400', 653);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (89, 'Boeing 777', 637);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (90, 'Mitsubishi MRJ90', 408);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (91, 'Bombardier CRJ700', 592);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (92, 'Boeing 777', 647);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (93, 'Boeing 737', 469);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (94, 'Boeing 787 Dreamliner', 671);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (95, 'Dornier Do 328', 531);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (96, 'Bombardier CS300', 549);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (97, 'Boeing 747', 561);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (98, 'Airbus A380', 601);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (99, 'Xian MA60', 507);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (100, 'Embraer 190', 605);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (101, 'Comac C919', 540);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (102, 'Mitsubishi MRJ90', 691);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (103, 'Dornier Do 328', 455);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (104, 'Boeing 737', 626);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (105, 'Mitsubishi MRJ90', 650);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (106, 'Bombardier CRJ700', 400);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (107, 'Boeing 777', 562);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (108, 'Bombardier CRJ700', 625);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (109, 'De Havilland Canada DHC-8-400', 617);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (110, 'Airbus A380', 450);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (111, 'Antonov An-148', 424);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (112, 'Boeing 777', 602);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (113, 'Comac C919', 683);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (114, 'Xian MA60', 565);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (115, 'Airbus A220', 531);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (116, 'Airbus A350', 498);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (117, 'Xian MA60', 635);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (118, 'Airbus A380', 656);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (119, 'Bombardier CRJ700', 602);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (120, 'Sukhoi Superjet 100', 403);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (121, 'Airbus A320', 412);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (122, 'Airbus A220', 648);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (123, 'Mitsubishi MRJ90', 558);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (124, 'Comac C919', 400);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (125, 'ATR 72', 624);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (126, 'Comac C919', 587);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (127, 'Airbus A350', 563);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (128, 'Bombardier CS300', 589);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (129, 'Airbus A320', 432);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (130, 'Embraer 190', 454);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (131, 'Bombardier CRJ700', 536);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (132, 'Sukhoi Superjet 100', 653);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (133, 'Boeing 737', 517);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (134, 'Airbus A350', 578);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (135, 'Airbus A330', 546);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (136, 'De Havilland Canada DHC-8-400', 431);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (137, 'Boeing 747', 540);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (138, 'Embraer 190', 646);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (139, 'Boeing 777', 619);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (140, 'Airbus A320', 446);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (141, 'Airbus A380', 682);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (142, 'Sukhoi Superjet 100', 663);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (143, 'Boeing 787 Dreamliner', 499);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (144, 'Dornier Do 328', 586);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (145, 'Xian MA60', 411);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (146, 'ATR 72', 612);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (147, 'Airbus A320', 500);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (148, 'Airbus A380', 679);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (149, 'Antonov An-148', 678);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (150, 'Comac C919', 568);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (151, 'Bombardier CS300', 428);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (152, 'De Havilland Canada DHC-8-400', 580);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (153, 'Bombardier CRJ700', 455);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (154, 'Bombardier CRJ700', 655);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (155, 'Boeing 747', 532);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (156, 'Boeing 747', 604);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (157, 'Bombardier CRJ700', 601);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (158, 'Airbus A330', 584);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (159, 'Xian MA60', 405);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (160, 'Embraer 190', 520);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (161, 'Xian MA60', 668);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (162, 'Boeing 777', 662);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (163, 'Dornier Do 328', 474);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (164, 'ATR 72', 653);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (165, 'Boeing 737', 563);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (166, 'Xian MA60', 455);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (167, 'Boeing 737', 505);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (168, 'Mitsubishi MRJ90', 427);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (169, 'Boeing 737', 537);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (170, 'Mitsubishi MRJ90', 681);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (171, 'De Havilland Canada DHC-8-400', 693);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (172, 'Boeing 787 Dreamliner', 623);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (173, 'Embraer 190', 521);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (174, 'Embraer 190', 469);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (175, 'Mitsubishi MRJ90', 643);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (176, 'De Havilland Canada DHC-8-400', 435);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (177, 'Airbus A380', 419);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (178, 'Airbus A350', 466);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (179, 'Airbus A220', 454);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (180, 'Airbus A380', 614);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (181, 'Antonov An-148', 525);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (182, 'Airbus A380', 597);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (183, 'Embraer 190', 502);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (184, 'Boeing 737', 691);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (185, 'Dornier Do 328', 422);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (186, 'Airbus A380', 470);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (187, 'Embraer 190', 580);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (188, 'Airbus A220', 435);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (189, 'Airbus A320', 500);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (190, 'ATR 72', 557);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (191, 'Boeing 747', 528);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (192, 'Boeing 747', 426);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (193, 'Embraer 190', 505);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (194, 'Bombardier CRJ700', 633);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (195, 'Airbus A320', 478);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (196, 'Boeing 777', 413);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (197, 'Xian MA60', 502);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (198, 'Boeing 787 Dreamliner', 693);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (199, 'Bombardier CS300', 494);
insert into Aircrafts (Aircraft_ID, Aircraft_Type, Capacity) values (200, 'Boeing 737', 471);
