insert into Airlines (Airline_ID, Airline_Name) values (1, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (2, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (3, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (4, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (5, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (6, 'Emirates');
insert into Airlines (Airline_ID, Airline_Name) values (7, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (8, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (9, 'United Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (10, 'Air France-KLM Group');
insert into Airlines (Airline_ID, Airline_Name) values (11, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (12, 'Delta Air Lines');
insert into Airlines (Airline_ID, Airline_Name) values (13, 'Air France-KLM Group');
insert into Airlines (Airline_ID, Airline_Name) values (14, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (15, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (16, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (17, 'Emirates');
insert into Airlines (Airline_ID, Airline_Name) values (18, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (19, 'International Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (20, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (21, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (22, 'ANA Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (23, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (24, 'Air France-KLM Group');
insert into Airlines (Airline_ID, Airline_Name) values (25, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (26, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (27, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (28, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (29, 'International Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (30, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (31, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (32, 'International Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (33, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (34, 'United Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (35, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (36, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (37, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (38, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (39, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (40, 'Ryanair Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (41, 'Delta Air Lines');
insert into Airlines (Airline_ID, Airline_Name) values (42, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (43, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (44, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (45, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (46, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (47, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (48, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (49, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (50, 'Wizz Air Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (51, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (52, 'Wizz Air Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (53, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (54, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (55, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (56, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (57, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (58, 'Ryanair Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (59, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (60, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (61, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (62, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (63, 'Emirates');
insert into Airlines (Airline_ID, Airline_Name) values (64, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (65, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (66, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (67, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (68, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (69, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (70, 'Ryanair Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (71, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (72, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (73, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (74, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (75, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (76, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (77, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (78, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (79, 'United Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (80, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (81, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (82, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (83, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (84, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (85, 'Delta Air Lines');
insert into Airlines (Airline_ID, Airline_Name) values (86, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (87, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (88, 'Wizz Air Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (89, 'Ryanair Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (90, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (91, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (92, 'United Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (93, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (94, 'Wizz Air Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (95, 'Wizz Air Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (96, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (97, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (98, 'Ryanair Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (99, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (100, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (101, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (102, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (103, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (104, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (105, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (106, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (107, 'ANA Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (108, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (109, 'United Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (110, 'Wizz Air Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (111, 'United Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (112, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (113, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (114, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (115, 'International Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (116, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (117, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (118, 'International Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (119, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (120, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (121, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (122, 'ANA Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (123, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (124, 'International Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (125, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (126, 'International Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (127, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (128, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (129, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (130, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (131, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (132, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (133, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (134, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (135, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (136, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (137, 'Wizz Air Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (138, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (139, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (140, 'Wizz Air Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (141, 'Air France-KLM Group');
insert into Airlines (Airline_ID, Airline_Name) values (142, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (143, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (144, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (145, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (146, 'ANA Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (147, 'Air France-KLM Group');
insert into Airlines (Airline_ID, Airline_Name) values (148, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (149, 'United Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (150, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (151, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (152, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (153, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (154, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (155, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (156, 'Air France-KLM Group');
insert into Airlines (Airline_ID, Airline_Name) values (157, 'Ryanair Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (158, 'Air France-KLM Group');
insert into Airlines (Airline_ID, Airline_Name) values (159, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (160, 'Ryanair Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (161, 'Emirates');
insert into Airlines (Airline_ID, Airline_Name) values (162, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (163, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (164, 'Wizz Air Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (165, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (166, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (167, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (168, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (169, 'ANA Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (170, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (171, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (172, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (173, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (174, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (175, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (176, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (177, 'Emirates');
insert into Airlines (Airline_ID, Airline_Name) values (178, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (179, 'Southwest Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (180, 'China Eastern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (181, 'Ryanair Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (182, 'IndiGo');
insert into Airlines (Airline_ID, Airline_Name) values (183, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (184, 'Air France-KLM Group');
insert into Airlines (Airline_ID, Airline_Name) values (185, 'Turkish Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (186, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (187, 'Avianca Holdings');
insert into Airlines (Airline_ID, Airline_Name) values (188, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (189, 'United Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (190, 'LATAM Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (191, 'China Southern Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (192, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (193, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (194, 'United Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (195, 'International Airlines Group');
insert into Airlines (Airline_ID, Airline_Name) values (196, 'American Airlines');
insert into Airlines (Airline_ID, Airline_Name) values (197, 'Lufthansa Group');
insert into Airlines (Airline_ID, Airline_Name) values (198, 'Alaska Air Group');
insert into Airlines (Airline_ID, Airline_Name) values (199, 'JetBlue Airways');
insert into Airlines (Airline_ID, Airline_Name) values (200, 'Air France-KLM Group');
