insert into Airports (Airport_ID, Airport_Name, Location) values (1, 'CKC', 'Korczew');
insert into Airports (Airport_ID, Airport_Name, Location) values (2, 'YBR', 'Widuchowa');
insert into Airports (Airport_ID, Airport_Name, Location) values (3, 'MRA', 'Pinayagan Norte');
insert into Airports (Airport_ID, Airport_Name, Location) values (4, 'KIT', 'Rat Burana');
insert into Airports (Airport_ID, Airport_Name, Location) values (5, 'TKF', 'Düsseldorf');
insert into Airports (Airport_ID, Airport_Name, Location) values (6, 'DAT', 'Cherepovets');
insert into Airports (Airport_ID, Airport_Name, Location) values (7, 'PDO', 'Gœsdorf');
insert into Airports (Airport_ID, Airport_Name, Location) values (8, 'YPX', 'Kolaka');
insert into Airports (Airport_ID, Airport_Name, Location) values (9, 'ECN', 'Taldyqorghan');
insert into Airports (Airport_ID, Airport_Name, Location) values (10, 'BNR', 'Ruzhany');
insert into Airports (Airport_ID, Airport_Name, Location) values (11, 'TRA', 'Tamano');
insert into Airports (Airport_ID, Airport_Name, Location) values (12, 'GGO', 'Clearwater');
insert into Airports (Airport_ID, Airport_Name, Location) values (13, 'YRB', 'New Sibonga');
insert into Airports (Airport_ID, Airport_Name, Location) values (14, 'REE', 'Shentang');
insert into Airports (Airport_ID, Airport_Name, Location) values (15, 'IXL', 'Milwaukee');
insert into Airports (Airport_ID, Airport_Name, Location) values (16, 'ASY', 'Huayllo');
insert into Airports (Airport_ID, Airport_Name, Location) values (17, 'KOX', 'Villa Ángela');
insert into Airports (Airport_ID, Airport_Name, Location) values (18, 'CLX', 'Ādilpur');
insert into Airports (Airport_ID, Airport_Name, Location) values (19, 'SAE', 'Castellon De La Plana/Castello De La Pla');
insert into Airports (Airport_ID, Airport_Name, Location) values (20, 'MCW', 'Nishinoomote');
insert into Airports (Airport_ID, Airport_Name, Location) values (21, 'WBM', 'Padasono');
insert into Airports (Airport_ID, Airport_Name, Location) values (22, 'GEA', 'Kabar Utara');
insert into Airports (Airport_ID, Airport_Name, Location) values (23, 'THA', 'Lisala');
insert into Airports (Airport_ID, Airport_Name, Location) values (24, 'AXX', 'Plateliai');
insert into Airports (Airport_ID, Airport_Name, Location) values (25, 'GCI', 'Cinangka');
insert into Airports (Airport_ID, Airport_Name, Location) values (26, 'KKG', 'Köping');
insert into Airports (Airport_ID, Airport_Name, Location) values (27, 'BGR', 'Pangtangis Dajah');
insert into Airports (Airport_ID, Airport_Name, Location) values (28, 'MFG', 'Bijela');
insert into Airports (Airport_ID, Airport_Name, Location) values (29, 'MZC', 'Herrljunga');
insert into Airports (Airport_ID, Airport_Name, Location) values (30, 'BRQ', 'Kaavi');
insert into Airports (Airport_ID, Airport_Name, Location) values (31, 'HPH', 'Świecie');
insert into Airports (Airport_ID, Airport_Name, Location) values (32, 'NAV', 'Shatou');
insert into Airports (Airport_ID, Airport_Name, Location) values (33, 'GVL', 'Novi Šeher');
insert into Airports (Airport_ID, Airport_Name, Location) values (34, 'ZIN', 'Rockford');
insert into Airports (Airport_ID, Airport_Name, Location) values (35, 'GVL', 'Grand Rapids');
insert into Airports (Airport_ID, Airport_Name, Location) values (36, 'PGZ', 'Tandaltī');
insert into Airports (Airport_ID, Airport_Name, Location) values (37, 'THG', 'Hamar');
insert into Airports (Airport_ID, Airport_Name, Location) values (38, 'SFR', 'Banjar Ponggang');
insert into Airports (Airport_ID, Airport_Name, Location) values (39, 'PEZ', 'Valcheta');
insert into Airports (Airport_ID, Airport_Name, Location) values (40, 'PAM', 'Longkou');
insert into Airports (Airport_ID, Airport_Name, Location) values (41, 'PZU', 'Óbidos');
insert into Airports (Airport_ID, Airport_Name, Location) values (42, 'ARY', 'Ruy Barbosa');
insert into Airports (Airport_ID, Airport_Name, Location) values (43, 'LMT', 'Starobachaty');
insert into Airports (Airport_ID, Airport_Name, Location) values (44, 'BJJ', 'Delvinë');
insert into Airports (Airport_ID, Airport_Name, Location) values (45, 'DLK', 'Hacıqabul');
insert into Airports (Airport_ID, Airport_Name, Location) values (46, 'MCO', 'Naberera');
insert into Airports (Airport_ID, Airport_Name, Location) values (47, 'JDH', 'Zhengcun');
insert into Airports (Airport_ID, Airport_Name, Location) values (48, 'POI', 'Västra Frölunda');
insert into Airports (Airport_ID, Airport_Name, Location) values (49, 'JEF', 'Liangdang Chengguanzhen');
insert into Airports (Airport_ID, Airport_Name, Location) values (50, 'BVC', 'Nantes');
insert into Airports (Airport_ID, Airport_Name, Location) values (51, 'ULO', 'Tacoma');
insert into Airports (Airport_ID, Airport_Name, Location) values (52, 'KHI', 'Alfortville');
insert into Airports (Airport_ID, Airport_Name, Location) values (53, 'CMS', 'Malakwal City');
insert into Airports (Airport_ID, Airport_Name, Location) values (54, 'WNS', 'Lodan Wetan');
insert into Airports (Airport_ID, Airport_Name, Location) values (55, 'QUG', 'Starý Bohumín');
insert into Airports (Airport_ID, Airport_Name, Location) values (56, 'SJP', 'Palpalá');
insert into Airports (Airport_ID, Airport_Name, Location) values (57, 'FNT', 'Klemunan');
insert into Airports (Airport_ID, Airport_Name, Location) values (58, 'RIZ', 'Francisco I Madero');
insert into Airports (Airport_ID, Airport_Name, Location) values (59, 'RKV', 'Oslo');
insert into Airports (Airport_ID, Airport_Name, Location) values (60, 'SSZ', 'Langchi');
insert into Airports (Airport_ID, Airport_Name, Location) values (61, 'PAF', 'Santa Rosa');
insert into Airports (Airport_ID, Airport_Name, Location) values (62, 'SMS', 'Oxelösund');
insert into Airports (Airport_ID, Airport_Name, Location) values (63, 'MBY', 'Thị Trấn Việt Quang');
insert into Airports (Airport_ID, Airport_Name, Location) values (64, 'ELC', 'Hāgere Selam');
insert into Airports (Airport_ID, Airport_Name, Location) values (65, 'MBS', 'Féres');
insert into Airports (Airport_ID, Airport_Name, Location) values (66, 'MRR', 'Ocoyo');
insert into Airports (Airport_ID, Airport_Name, Location) values (67, 'NZC', 'Semongkat');
insert into Airports (Airport_ID, Airport_Name, Location) values (68, 'DOC', 'Krajan Karangsari');
insert into Airports (Airport_ID, Airport_Name, Location) values (69, 'SBW', 'Talisay');
insert into Airports (Airport_ID, Airport_Name, Location) values (70, 'GLZ', 'Xiangqiao');
insert into Airports (Airport_ID, Airport_Name, Location) values (71, 'TSH', 'Beizi');
insert into Airports (Airport_ID, Airport_Name, Location) values (72, 'FRQ', 'Palmas De Gran Canaria, Las');
insert into Airports (Airport_ID, Airport_Name, Location) values (73, 'ANF', 'Cikalong');
insert into Airports (Airport_ID, Airport_Name, Location) values (74, 'SMN', 'Tahe');
insert into Airports (Airport_ID, Airport_Name, Location) values (75, 'KSJ', 'Duanjia');
insert into Airports (Airport_ID, Airport_Name, Location) values (76, 'ZCL', 'Taytayan');
insert into Airports (Airport_ID, Airport_Name, Location) values (77, 'REU', 'Huangjing');
insert into Airports (Airport_ID, Airport_Name, Location) values (78, 'AWA', 'Suna');
insert into Airports (Airport_ID, Airport_Name, Location) values (79, 'CMD', 'Labuhankananga');
insert into Airports (Airport_ID, Airport_Name, Location) values (80, 'HLO', 'Kāshān');
insert into Airports (Airport_ID, Airport_Name, Location) values (81, 'NKB', 'Castlepollard');
insert into Airports (Airport_ID, Airport_Name, Location) values (82, 'SNY', 'Bebandem');
insert into Airports (Airport_ID, Airport_Name, Location) values (83, 'KNF', 'Kyzyl-Oktyabr’skiy');
insert into Airports (Airport_ID, Airport_Name, Location) values (84, 'ULE', 'Dire Dawa');
insert into Airports (Airport_ID, Airport_Name, Location) values (85, 'IOA', 'Lieqiao');
insert into Airports (Airport_ID, Airport_Name, Location) values (86, 'GRM', 'Tessaoua');
insert into Airports (Airport_ID, Airport_Name, Location) values (87, 'BMV', 'Paris 07');
insert into Airports (Airport_ID, Airport_Name, Location) values (88, 'DAY', 'Broby');
insert into Airports (Airport_ID, Airport_Name, Location) values (89, 'PMF', 'Paris 09');
insert into Airports (Airport_ID, Airport_Name, Location) values (90, 'ATH', 'Petani');
insert into Airports (Airport_ID, Airport_Name, Location) values (91, 'SAA', 'Laventure');
insert into Airports (Airport_ID, Airport_Name, Location) values (92, 'SJO', 'Linghu');
insert into Airports (Airport_ID, Airport_Name, Location) values (93, 'BKM', 'Arroyo Naranjo');
insert into Airports (Airport_ID, Airport_Name, Location) values (94, 'MTF', 'Pulap');
insert into Airports (Airport_ID, Airport_Name, Location) values (95, 'GDN', 'Changuillo');
insert into Airports (Airport_ID, Airport_Name, Location) values (96, 'WDR', 'Ochobo');
insert into Airports (Airport_ID, Airport_Name, Location) values (97, 'CPF', 'Drobin');
insert into Airports (Airport_ID, Airport_Name, Location) values (98, 'SJA', 'Montceau-les-Mines');
insert into Airports (Airport_ID, Airport_Name, Location) values (99, 'VER', 'Besançon');
insert into Airports (Airport_ID, Airport_Name, Location) values (100, 'MUI', 'Atins');
insert into Airports (Airport_ID, Airport_Name, Location) values (101, 'TPL', 'Marull');
insert into Airports (Airport_ID, Airport_Name, Location) values (102, 'IXZ', 'Ujungpangkah');
insert into Airports (Airport_ID, Airport_Name, Location) values (103, 'GSE', 'Xiaolongmen');
insert into Airports (Airport_ID, Airport_Name, Location) values (104, 'OKN', 'Allen');
insert into Airports (Airport_ID, Airport_Name, Location) values (105, 'NLL', 'Kabanga');
insert into Airports (Airport_ID, Airport_Name, Location) values (106, 'RAM', 'Putukrejo');
insert into Airports (Airport_ID, Airport_Name, Location) values (107, 'RBD', 'Sukasada');
insert into Airports (Airport_ID, Airport_Name, Location) values (108, 'POS', 'Chacarita');
insert into Airports (Airport_ID, Airport_Name, Location) values (109, 'TZM', 'Wanxian');
insert into Airports (Airport_ID, Airport_Name, Location) values (110, 'IPE', 'Xinghua');
insert into Airports (Airport_ID, Airport_Name, Location) values (111, 'BTZ', 'Kuanfeu');
insert into Airports (Airport_ID, Airport_Name, Location) values (112, 'PZO', 'Bralin');
insert into Airports (Airport_ID, Airport_Name, Location) values (113, 'DOI', 'Lanyi');
insert into Airports (Airport_ID, Airport_Name, Location) values (114, 'YTS', 'Kowingir');
insert into Airports (Airport_ID, Airport_Name, Location) values (115, 'LUP', 'Budapest');
insert into Airports (Airport_ID, Airport_Name, Location) values (116, 'AAB', 'Pajung');
insert into Airports (Airport_ID, Airport_Name, Location) values (117, 'ECI', 'Estrada');
insert into Airports (Airport_ID, Airport_Name, Location) values (118, 'YRD', 'Uddevalla');
insert into Airports (Airport_ID, Airport_Name, Location) values (119, '0', 'Qalandiyā');
insert into Airports (Airport_ID, Airport_Name, Location) values (120, 'KCE', 'Pindushi');
insert into Airports (Airport_ID, Airport_Name, Location) values (121, 'DIN', 'Segovia');
insert into Airports (Airport_ID, Airport_Name, Location) values (122, 'RUA', 'Custóias');
insert into Airports (Airport_ID, Airport_Name, Location) values (123, 'QHN', 'Qimantage');
insert into Airports (Airport_ID, Airport_Name, Location) values (124, 'KCO', 'Ijūin');
insert into Airports (Airport_ID, Airport_Name, Location) values (125, 'NAI', 'Chengxi');
insert into Airports (Airport_ID, Airport_Name, Location) values (126, 'CHZ', 'Ainaži');
insert into Airports (Airport_ID, Airport_Name, Location) values (127, 'HUH', 'Podgortsy');
insert into Airports (Airport_ID, Airport_Name, Location) values (128, 'BAI', 'Markaz al Marīr');
insert into Airports (Airport_ID, Airport_Name, Location) values (129, 'AYK', 'Al Jawf');
insert into Airports (Airport_ID, Airport_Name, Location) values (130, 'HHI', 'Nangewer');
insert into Airports (Airport_ID, Airport_Name, Location) values (131, 'UIQ', 'Al Bāţinah');
insert into Airports (Airport_ID, Airport_Name, Location) values (132, 'WHS', 'Tomepampa');
insert into Airports (Airport_ID, Airport_Name, Location) values (133, 'ARQ', 'Klos');
insert into Airports (Airport_ID, Airport_Name, Location) values (134, 'ASC', 'Vännäs');
insert into Airports (Airport_ID, Airport_Name, Location) values (135, 'KNG', 'Lille');
insert into Airports (Airport_ID, Airport_Name, Location) values (136, 'MFS', 'Cipeundeuy');
insert into Airports (Airport_ID, Airport_Name, Location) values (137, 'SIJ', 'Dallas');
insert into Airports (Airport_ID, Airport_Name, Location) values (138, 'GNR', 'Nanbin');
insert into Airports (Airport_ID, Airport_Name, Location) values (139, 'VDS', 'Az Zawr');
insert into Airports (Airport_ID, Airport_Name, Location) values (140, 'SCK', 'Minūf');
insert into Airports (Airport_ID, Airport_Name, Location) values (141, 'OSK', 'Huangdao');
insert into Airports (Airport_ID, Airport_Name, Location) values (142, 'VAI', 'Tromsø');
insert into Airports (Airport_ID, Airport_Name, Location) values (143, 'QEF', 'Solec Nad Wisłą');
insert into Airports (Airport_ID, Airport_Name, Location) values (144, 'BHX', 'Västerås');
insert into Airports (Airport_ID, Airport_Name, Location) values (145, 'BNC', 'Tekstil’shchiki');
insert into Airports (Airport_ID, Airport_Name, Location) values (146, 'CCJ', 'Sergio Osmeña Sr');
insert into Airports (Airport_ID, Airport_Name, Location) values (147, 'SHD', 'Lanlacuni Bajo');
insert into Airports (Airport_ID, Airport_Name, Location) values (148, 'ZSE', 'Américo Brasiliense');
insert into Airports (Airport_ID, Airport_Name, Location) values (149, 'NRB', 'Vila Nova');
insert into Airports (Airport_ID, Airport_Name, Location) values (150, 'DPB', 'Huilong');
insert into Airports (Airport_ID, Airport_Name, Location) values (151, 'ASF', 'Mayang');
insert into Airports (Airport_ID, Airport_Name, Location) values (152, 'LGF', 'Gifu-shi');
insert into Airports (Airport_ID, Airport_Name, Location) values (153, 'HEI', 'Chepo');
insert into Airports (Airport_ID, Airport_Name, Location) values (154, 'SQC', 'Serra Talhada');
insert into Airports (Airport_ID, Airport_Name, Location) values (155, 'LIN', 'Miaoshi');
insert into Airports (Airport_ID, Airport_Name, Location) values (156, 'EMN', 'Bayanbulag');
insert into Airports (Airport_ID, Airport_Name, Location) values (157, 'LLF', 'Huangmu');
insert into Airports (Airport_ID, Airport_Name, Location) values (158, 'BAJ', 'Abū Sunbul');
insert into Airports (Airport_ID, Airport_Name, Location) values (159, 'GAY', 'Rokytnice');
insert into Airports (Airport_ID, Airport_Name, Location) values (160, 'MFU', 'Huishangang');
insert into Airports (Airport_ID, Airport_Name, Location) values (161, 'JNB', 'Yong’an');
insert into Airports (Airport_ID, Airport_Name, Location) values (162, 'FAU', 'Partesh');
insert into Airports (Airport_ID, Airport_Name, Location) values (163, 'FIH', 'Mossendjo');
insert into Airports (Airport_ID, Airport_Name, Location) values (164, '0', 'Longsheng');
insert into Airports (Airport_ID, Airport_Name, Location) values (165, 'JNG', 'Clones');
insert into Airports (Airport_ID, Airport_Name, Location) values (166, 'SJB', 'Schirmeck');
insert into Airports (Airport_ID, Airport_Name, Location) values (167, 'CAM', 'Safi');
insert into Airports (Airport_ID, Airport_Name, Location) values (168, 'TBS', 'Shanghe');
insert into Airports (Airport_ID, Airport_Name, Location) values (169, 'GSJ', 'Miraflores');
insert into Airports (Airport_ID, Airport_Name, Location) values (170, 'AZG', 'Saint-Denis');
insert into Airports (Airport_ID, Airport_Name, Location) values (171, 'QNY', 'Sinjhoro');
insert into Airports (Airport_ID, Airport_Name, Location) values (172, 'ATZ', 'Xanxerê');
insert into Airports (Airport_ID, Airport_Name, Location) values (173, 'KOJ', 'Placencia');
insert into Airports (Airport_ID, Airport_Name, Location) values (174, 'MTU', 'Manokwari');
insert into Airports (Airport_ID, Airport_Name, Location) values (175, 'LKW', 'Velizh');
insert into Airports (Airport_ID, Airport_Name, Location) values (176, 'CXN', 'Dejilin');
insert into Airports (Airport_ID, Airport_Name, Location) values (177, 'MAH', 'Banjar Laing');
insert into Airports (Airport_ID, Airport_Name, Location) values (178, 'ATL', 'Dongxin');
insert into Airports (Airport_ID, Airport_Name, Location) values (179, 'TNS', 'Subottsi');
insert into Airports (Airport_ID, Airport_Name, Location) values (180, 'PKT', 'Baitoa');
insert into Airports (Airport_ID, Airport_Name, Location) values (181, 'XGN', 'Hayang');
insert into Airports (Airport_ID, Airport_Name, Location) values (182, 'YST', 'Trenton');
insert into Airports (Airport_ID, Airport_Name, Location) values (183, 'YCW', 'Guli');
insert into Airports (Airport_ID, Airport_Name, Location) values (184, 'SYV', 'Limache');
insert into Airports (Airport_ID, Airport_Name, Location) values (185, 'NME', 'Longfeng');
insert into Airports (Airport_ID, Airport_Name, Location) values (186, 'PZH', 'Shuiyuan');
insert into Airports (Airport_ID, Airport_Name, Location) values (187, 'ZER', 'Roshchino');
insert into Airports (Airport_ID, Airport_Name, Location) values (188, 'ORD', 'Tejar');
insert into Airports (Airport_ID, Airport_Name, Location) values (189, 'TXN', 'Villasis');
insert into Airports (Airport_ID, Airport_Name, Location) values (190, 'AMB', 'Pingshan');
insert into Airports (Airport_ID, Airport_Name, Location) values (191, 'SAQ', 'Boa Esperança');
insert into Airports (Airport_ID, Airport_Name, Location) values (192, 'BFL', 'Vårby');
insert into Airports (Airport_ID, Airport_Name, Location) values (193, 'MKG', 'Mayuan');
insert into Airports (Airport_ID, Airport_Name, Location) values (194, 'NJC', 'Paris 08');
insert into Airports (Airport_ID, Airport_Name, Location) values (195, 'OSD', 'Kitango');
insert into Airports (Airport_ID, Airport_Name, Location) values (196, 'BCC', 'Hisings Kärra');
insert into Airports (Airport_ID, Airport_Name, Location) values (197, 'LDX', 'Hinvi');
insert into Airports (Airport_ID, Airport_Name, Location) values (198, 'GMV', 'Cahul');
insert into Airports (Airport_ID, Airport_Name, Location) values (199, 'DOR', 'Velenje');
insert into Airports (Airport_ID, Airport_Name, Location) values (200, 'XBB', 'Mataquescuintla');
