insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (1, 'Laney Pitman', 'Safety and Security Officer', '818-671-0897');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (2, 'Spenser Medendorp', 'Safety and Security Officer', '782-719-9173');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (3, 'Michaeline Bradder', 'Purser', '848-255-7330');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (4, 'Hoebart Cessford', 'In-Flight Chef', '700-485-1662');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (5, 'Catha Pearmine', 'Purser', '666-988-0570');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (6, 'Shaun Latham', 'First Officer', '126-419-3865');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (7, 'Yolane Attaway', 'In-Flight Chef', '950-917-9324');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (8, 'Ree Truin', 'Purser', '178-736-9034');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (9, 'Roma Aglione', 'Safety and Security Officer', '307-275-8440');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (10, 'Douglass Stoffersen', 'Purser', '456-758-6613');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (11, 'Laurie Delamere', 'Purser', '415-938-4729');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (12, 'Christopher Tweed', 'Pilot', '662-893-8735');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (13, 'Inga Carlozzi', 'Flight Attendant', '542-499-7634');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (14, 'Cortney Liff', 'In-Flight Chef', '109-897-0927');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (15, 'Nariko Davson', 'Pilot', '785-254-6340');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (16, 'Mariya Ivashinnikov', 'Pilot', '956-243-0894');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (17, 'Melitta Dominici', 'In-Flight Chef', '693-349-4228');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (18, 'Eryn Parsons', 'Purser', '824-652-4784');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (19, 'Catarina Breem', 'Pilot', '457-744-2480');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (20, 'Celle Delion', 'Copilot', '620-905-4876');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (21, 'Quinlan Yanukhin', 'Lead Flight Attendant', '706-168-5320');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (22, 'Putnem Louedey', 'Pilot', '524-168-3719');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (23, 'Bianca Dutton', 'First Officer', '231-200-5423');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (24, 'Jody Bocking', 'Flight Attendant', '611-336-6890');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (25, 'Eduardo Fleg', 'In-Flight Chef', '861-891-8519');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (26, 'Alane Rothon', 'Purser', '617-634-2616');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (27, 'Dominique Fleetham', 'Purser', '143-464-8908');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (28, 'Hyman Tolcher', 'Safety and Security Officer', '505-121-0554');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (29, 'Marlane Scay', 'Copilot', '182-480-7570');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (30, 'Willey Khidr', 'Flight Attendant', '900-100-8575');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (31, 'Virginie Oake', 'Pilot', '629-515-2588');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (32, 'Lydia Zimmermeister', 'Safety and Security Officer', '747-886-6010');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (33, 'Junia Favela', 'First Officer', '742-305-9630');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (34, 'Zacherie O''Hern', 'First Officer', '801-546-4970');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (35, 'Ervin Troyes', 'Lead Flight Attendant', '992-634-3477');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (36, 'Chance Moresby', 'Pilot', '916-732-9364');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (37, 'Stanislaus Pothbury', 'Lead Flight Attendant', '440-640-9345');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (38, 'Gerry Kingaby', 'Purser', '860-491-5287');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (39, 'Jordana Dominey', 'First Officer', '738-862-1091');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (40, 'Koo Radnage', 'In-Flight Chef', '562-669-2892');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (41, 'Chelsy Bartoli', 'Copilot', '456-738-8984');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (42, 'Tony Wellesley', 'Pilot', '323-646-6173');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (43, 'Annette Dahle', 'Flight Attendant', '239-612-7875');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (44, 'Raymund Burgan', 'Purser', '635-918-9507');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (45, 'Concordia Balme', 'Safety and Security Officer', '948-525-5229');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (46, 'Basilius Cordelette', 'Pilot', '267-513-6793');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (47, 'Mag Jessop', 'Purser', '315-189-8583');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (48, 'Kip Cochet', 'Flight Attendant', '350-172-8595');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (49, 'Sayre Lehrmann', 'Flight Attendant', '209-196-9597');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (50, 'Ilse Margiotta', 'Lead Flight Attendant', '235-806-0514');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (51, 'Zsazsa Yukhov', 'Pilot', '960-860-3546');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (52, 'Kaitlynn Tour', 'In-Flight Chef', '899-497-0787');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (53, 'Ninette Myton', 'Lead Flight Attendant', '626-922-2527');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (54, 'Eleonora Lewknor', 'Safety and Security Officer', '963-377-9576');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (55, 'Raina Panther', 'Purser', '999-751-1393');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (56, 'Eddy Rosser', 'Pilot', '626-591-1333');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (57, 'Rowen Fetteplace', 'First Officer', '983-498-0272');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (58, 'Nathalie Standage', 'Flight Attendant', '906-429-3433');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (59, 'Meg Machen', 'First Officer', '599-457-2720');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (60, 'Elga Bartak', 'In-Flight Chef', '646-955-1712');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (61, 'Bee Lawee', 'First Officer', '868-711-3605');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (62, 'Claudetta Alenikov', 'First Officer', '761-300-3961');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (63, 'Juan Mc Kellen', 'Purser', '682-426-8709');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (64, 'Mikael Osmant', 'Safety and Security Officer', '817-971-4454');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (65, 'Egan Probbing', 'First Officer', '572-234-3907');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (66, 'Peta Laverock', 'Safety and Security Officer', '759-530-4892');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (67, 'Clovis Dumbarton', 'Lead Flight Attendant', '439-391-3223');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (68, 'Martainn Itzakson', 'First Officer', '739-702-3070');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (69, 'Cicely Licari', 'Lead Flight Attendant', '314-498-6658');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (70, 'Heddie Elderbrant', 'Safety and Security Officer', '821-147-2846');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (71, 'Matilda Pikhno', 'Purser', '485-882-6908');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (72, 'Gracie Esmond', 'Pilot', '373-313-8199');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (73, 'Marley Kear', 'Pilot', '752-243-4808');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (74, 'Gabie Higbin', 'First Officer', '840-831-0552');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (75, 'Theressa Roscow', 'In-Flight Chef', '262-344-0656');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (76, 'Briggs Brunskill', 'Safety and Security Officer', '862-346-6657');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (77, 'Maggie Laslett', 'Copilot', '639-356-4206');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (78, 'Valene Goundry', 'Purser', '202-969-1917');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (79, 'Leonie Surtees', 'Purser', '797-716-8996');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (80, 'Flo Foye', 'Lead Flight Attendant', '337-342-8332');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (81, 'Carly Brissenden', 'First Officer', '777-245-1655');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (82, 'Osmund Anglish', 'In-Flight Chef', '483-663-0415');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (83, 'Magdalene Capstaff', 'In-Flight Chef', '890-762-5504');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (84, 'Truman Blown', 'Safety and Security Officer', '803-599-7131');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (85, 'Rollie Raynton', 'Purser', '101-319-7584');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (86, 'Salomi Goodings', 'Safety and Security Officer', '726-874-7685');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (87, 'Jeane Salvatore', 'Copilot', '725-902-1036');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (88, 'Alvie Bare', 'In-Flight Chef', '985-857-6283');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (89, 'Riobard Enderle', 'In-Flight Chef', '871-507-3106');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (90, 'Goraud Carloni', 'Purser', '305-604-6491');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (91, 'Henka Myers', 'Purser', '219-148-1456');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (92, 'Issi Doiley', 'Pilot', '584-455-9187');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (93, 'Elwira Aldington', 'First Officer', '499-129-4420');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (94, 'Ramon Schiersch', 'Lead Flight Attendant', '901-980-4246');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (95, 'Juan Jerrolt', 'Lead Flight Attendant', '211-796-6552');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (96, 'Haven Dreigher', 'Lead Flight Attendant', '991-151-6729');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (97, 'Jackelyn Wreath', 'First Officer', '544-715-6996');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (98, 'Lucretia Scarce', 'In-Flight Chef', '338-851-1632');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (99, 'Hana Edards', 'First Officer', '513-410-3301');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (100, 'Onfroi Gambell', 'Safety and Security Officer', '350-214-6789');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (101, 'Willette Wheelton', 'First Officer', '499-601-7709');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (102, 'Virginie Bauldrey', 'In-Flight Chef', '952-528-8053');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (103, 'Pooh O''Dee', 'Lead Flight Attendant', '150-101-1942');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (104, 'Carling Ritmeier', 'First Officer', '999-188-5945');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (105, 'Christan Glackin', 'In-Flight Chef', '780-701-2599');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (106, 'Josefina Fennick', 'First Officer', '346-123-7444');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (107, 'Lorianne Hedditch', 'Pilot', '270-125-0586');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (108, 'Marijo Geri', 'First Officer', '988-178-9659');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (109, 'Nickie Pedro', 'Lead Flight Attendant', '356-992-0008');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (110, 'Rodrick Hutchens', 'Safety and Security Officer', '795-348-9741');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (111, 'Pedro Trenear', 'In-Flight Chef', '254-347-6450');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (112, 'Peyter Romme', 'In-Flight Chef', '845-846-9181');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (113, 'Janis Samweyes', 'Safety and Security Officer', '616-807-2225');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (114, 'Rudolfo Oty', 'In-Flight Chef', '497-908-5155');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (115, 'Amalie Nelsey', 'Purser', '204-509-7190');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (116, 'Sara-ann MacFadzan', 'First Officer', '388-519-4079');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (117, 'Deedee Clarridge', 'Pilot', '241-456-2809');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (118, 'Glyn Cordero', 'Copilot', '880-233-8323');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (119, 'Marne Haddrell', 'Purser', '659-652-9986');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (120, 'Bill Dilley', 'In-Flight Chef', '877-435-6542');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (121, 'Shandee Worstall', 'Pilot', '589-900-5125');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (122, 'Homere Shuttell', 'Safety and Security Officer', '785-712-1044');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (123, 'Kikelia Preedy', 'Copilot', '494-270-8270');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (124, 'Mick Cordy', 'Safety and Security Officer', '805-982-4485');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (125, 'Candra L''Hommee', 'First Officer', '153-481-4487');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (126, 'Dara Bethune', 'Pilot', '622-997-9609');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (127, 'Annemarie Bocking', 'Lead Flight Attendant', '855-668-5102');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (128, 'Cinderella Raubenheim', 'Flight Attendant', '165-526-7892');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (129, 'Cordy Wardle', 'In-Flight Chef', '319-455-9892');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (130, 'Mariana Balaisot', 'Flight Attendant', '873-469-7083');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (131, 'Terra Foulger', 'Pilot', '891-423-7544');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (132, 'Rickie Groucutt', 'In-Flight Chef', '173-249-8373');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (133, 'Bernadene Scoone', 'Purser', '494-370-5221');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (134, 'Kylie Ales', 'Pilot', '356-531-2095');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (135, 'Adelaida Cambling', 'Pilot', '444-935-7967');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (136, 'Shermy Braben', 'Flight Attendant', '330-205-9578');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (137, 'Genevieve Alkin', 'In-Flight Chef', '702-638-9096');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (138, 'Philipa Masters', 'Purser', '778-195-2059');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (139, 'Odelia Hawkins', 'Safety and Security Officer', '264-202-6547');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (140, 'Jonie Winyard', 'Flight Attendant', '805-616-6880');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (141, 'Mella Itter', 'Purser', '275-250-1647');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (142, 'Alon Risdall', 'First Officer', '436-328-6958');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (143, 'Flory Beams', 'Copilot', '256-242-5492');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (144, 'Winonah MacKnight', 'Lead Flight Attendant', '582-446-9015');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (145, 'Ninon Misken', 'Pilot', '418-629-8725');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (146, 'Travers Fredy', 'In-Flight Chef', '765-277-2284');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (147, 'Kakalina Grouen', 'Pilot', '726-667-9477');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (148, 'Giacinta Hegg', 'Safety and Security Officer', '852-116-5067');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (149, 'Jessy McIvor', 'Pilot', '788-241-8933');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (150, 'Emmeline Stanners', 'Lead Flight Attendant', '622-820-9770');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (151, 'Honey Cuberley', 'Copilot', '371-505-1927');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (152, 'Griffy Erskine', 'In-Flight Chef', '223-189-8858');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (153, 'Humfrey Langthorne', 'Purser', '309-233-9245');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (154, 'Brady Manilo', 'Lead Flight Attendant', '214-738-1068');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (155, 'Emmett Terry', 'Copilot', '970-190-0248');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (156, 'Zollie Cleynaert', 'Copilot', '558-795-9506');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (157, 'Reidar Tegler', 'Lead Flight Attendant', '363-798-3548');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (158, 'Lucias Barthel', 'First Officer', '208-498-3597');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (159, 'Ryan Scrinage', 'Purser', '718-528-9618');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (160, 'Rasia Botwright', 'Flight Attendant', '783-244-9052');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (161, 'Jo-anne Nelsey', 'Pilot', '944-684-0255');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (162, 'Dev Skipton', 'First Officer', '869-639-5880');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (163, 'Hilton Lemin', 'Copilot', '738-899-4621');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (164, 'Malachi Hutchins', 'Copilot', '626-979-4670');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (165, 'Jessamine Futter', 'Pilot', '752-843-2466');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (166, 'Silas Lent', 'Pilot', '537-402-8210');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (167, 'Antony Burgett', 'Purser', '375-306-4321');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (168, 'Gennifer Saterweyte', 'Purser', '902-748-6265');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (169, 'Val Glendenning', 'In-Flight Chef', '952-886-8006');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (170, 'Nowell Prince', 'Copilot', '613-490-5665');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (171, 'Felicia Algate', 'Flight Attendant', '524-865-4125');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (172, 'Timmie Kealey', 'Purser', '396-548-7004');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (173, 'Sergio Siege', 'Copilot', '347-192-0107');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (174, 'Abby Flores', 'Purser', '892-179-7062');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (175, 'Shaine Lidierth', 'Safety and Security Officer', '317-377-8766');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (176, 'Kikelia Fuchs', 'Flight Attendant', '441-609-8508');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (177, 'Minerva Ditter', 'Lead Flight Attendant', '612-837-1894');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (178, 'Cristiano Revington', 'Pilot', '252-696-9618');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (179, 'Tove Dahler', 'In-Flight Chef', '195-442-0133');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (180, 'Odey Proom', 'Purser', '655-253-1840');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (181, 'Waylin Sibley', 'Lead Flight Attendant', '408-271-9291');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (182, 'Sherlocke Kear', 'First Officer', '137-976-3607');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (183, 'Aigneis Grima', 'Flight Attendant', '681-529-0810');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (184, 'Maynord Rodolf', 'Copilot', '761-418-1273');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (185, 'Merwyn Garford', 'Flight Attendant', '231-891-4294');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (186, 'Carmelia Colly', 'Purser', '981-968-7721');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (187, 'Pris Saben', 'First Officer', '821-219-2057');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (188, 'Kristoforo Glading', 'Safety and Security Officer', '278-931-7878');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (189, 'Yorgo MacLardie', 'Safety and Security Officer', '677-556-3448');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (190, 'Carmine Bault', 'Lead Flight Attendant', '640-409-9951');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (191, 'Renell Rannigan', 'Purser', '688-821-0473');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (192, 'Tracey Crain', 'First Officer', '727-861-5338');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (193, 'Dione Birdis', 'In-Flight Chef', '633-465-0948');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (194, 'Eleni Blondell', 'Flight Attendant', '224-868-4442');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (195, 'Eldon Farherty', 'Copilot', '736-136-7739');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (196, 'Kristo Schiersch', 'First Officer', '714-936-0743');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (197, 'Idalina Harkess', 'In-Flight Chef', '130-254-8537');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (198, 'Constantia Boughey', 'Lead Flight Attendant', '388-518-2241');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (199, 'Tynan Breede', 'First Officer', '347-980-5227');
insert into CrewMembers (Crew_ID, Name, Role, Contact_Number) values (200, 'Roseline Lissandre', 'In-Flight Chef', '195-262-2779');
